{% set name = "rdt" %}
{% set version = "0.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rdt-{{ version }}.tar.gz
  sha256: c5a02b334b5c0ccefc548b0ea5720f29c26d9bec7e77b706f6779a1c2a00c5e8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.6,<3.10
  run:
    - numpy >=1.18.0,<2
    - pandas >=1.1,<1.1.5
    - psutil >=5.7,<6
    - python >=3.6,<3.10
    - scipy >=1.5.4,<2
    - scikit-learn >=0.24,<2
    - pyyaml >=5.4.1,<6

test:
  imports:
    - rdt
    - rdt.transformers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/RDT
  summary: Reversible Data Transforms
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - csala
    - fealho
    - katxiao
    - pvk-developer
