{% set name = "rdt" %}
{% set version = "1.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rdt-{{ version }}.tar.gz
  sha256: 59933cbefc086189bc1d233c6762506022b288e4869a181644b5a6a19f96e7be

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.7,<3.12
  run:
    - Faker >=10
    - numpy >=1.20.0,<2
    - pandas >=1.1.3,<2
    - psutil >=5.7,<6
    - python >=3.7,<3.12
    - scipy >=1.5.4,<2
    - scikit-learn >=0.24,<2

test:
  imports:
    - rdt
    - rdt.transformers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/RDT
  summary: Reversible Data Transforms
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - fealho
    - pvk-developer
    - frances-h
