{% set name = "rdt" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rdt-{{ version }}.tar.gz
  sha256: 0c2ce811b85a5515958f7e1e257c7eb5aaeb257e15e724b4c2895736c9892fe0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.7,<3.12
  run:
    - numpy >=1.20.0,<2
    - pandas >=1.1.3,<2
    - psutil >=5.7,<6
    - python >=3.7,<3.12
    - scipy >=1.5.4,<2
    - scikit-learn >=0.24,<2
    - Faker >=10

test:
  imports:
    - rdt
    - rdt.transformers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/RDT
  summary: Reversible Data Transforms
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - csala
    - fealho
    - katxiao
    - pvk-developer
