{% set name = "rdt" %}
{% set version = "1.18.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rdt-{{ version }}.tar.gz
  sha256: 768e812a9e2171c7523bb7e82ace5e658f1b76e7538e699a20f17010c8f3d2cb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python {{ python_min }}
  run:
    - Faker >=17, !=37.11.0
    - numpy >=1.21.0
    - pandas >=1.4.0
    - python >={{ python_min }},<3.14
    - python-dateutil >=2.9
    - scipy >=1.7.3,<2
    - scikit-learn >=1.0.2,<2

test:
  imports:
    - rdt
    - rdt.transformers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sdv-dev/RDT
  summary: Reversible Data Transforms
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - amontanez24
    - fealho
    - pvk-developer
    - frances-h
    - lajohn4747
    - rwedge
